@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant “:LogicManager” as LogicManager LOGIC_COLOR
participant “:AddressBookParser” as AddressBookParser LOGIC_COLOR
participant “:FindCommandParser” as FindCommandParser LOGIC_COLOR
participant ":FindCommand" as FindCommand LOGIC_COLOR
end box

[-> LogicManager : execute("dynamic Alex", commandBox)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(“dynamic Alex”, commandBox)
activate AddressBookParser

create FindCommandParser
AddressBookParser -> FindCommandParser
activate FindCommandParser

FindCommandParser -> AddressBookParser
deactivate FindCommandParser

AddressBookParser -> FindCommandParser : parse(“Alex")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand -> FindCommandParser
deactivate FindCommand

FindCommandParser -> AddressBookParser
deactivate FindCommandParser

AddressBookParser -> LogicManager
deactivate AddressBookParser

[<-- LogicManager
deactivate LogicManager
@enduml
