@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Meeting *--> Title
Meeting *--> Link
Meeting *--> Email
Meeting *--> StartTime
Meeting *--> Duration
Meeting *--> "*" Tag

@enduml
