@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package " Commons \n" #F4F6F6 {
Class JsonAdaptedTag
}

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedSocialMedia
}

package "MeetingsBook Storage" #F4F6F6{

Class "<<interface>>\nMeetingsBookStorage" as MeetingsBookStorage
Class JsonMeetingsBookStorage
Class JsonSerializableMeetingsBook
Class JsonAdaptedMeeting

}
}

Class HiddenOutside #FFFFFF
HiddenOutside .d.> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" MeetingsBookStorage
StorageManager -up-> "1" AddressBookStorage

Storage -right-|> UserPrefsStorage
Storage -right-|> AddressBookStorage
Storage -left-|> MeetingsBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonMeetingsBookStorage .up.|> MeetingsBookStorage

JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonSerializableAddressBook -l-> "*" JsonAdaptedTag
JsonAdaptedPerson --> "     \n      *" JsonAdaptedTag
JsonAdaptedPerson --> "*" JsonAdaptedSocialMedia

JsonMeetingsBookStorage ..> JsonSerializableMeetingsBook
JsonSerializableMeetingsBook --> "*" JsonAdaptedMeeting
JsonAdaptedMeeting --> "              \n*" JsonAdaptedTag

@enduml
