@startuml TargetClass
!include style.puml
skinparam classBackgroundColor MODEL_COLOR
skinparam groupInheritance 2

abstract class Target {
+{static} Target of(Name target, List<Person> persons)
+{static} Target of(Index target, List<Person> persons)
}

class NamedTarget extends Target
class IndexedTarget extends Target

@enduml
