@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ContactsTab
Class MeetingsTab
Class HelpTab
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside .d.> Ui

UiManager .l...|> Ui
UiManager -d-> "1" MainWindow
MainWindow *-d--> "1" ContactsTab
MainWindow *-d--> "1" MeetingsTab
MainWindow *-d--> "1" HelpTab

MainWindow -l-|> UiPart

UiManager -right-> Logic
MainWindow -right-> Logic

@enduml
