@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ContactsTab
Class MeetingsTab
Class HelpTab
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" ContactsTab
MainWindow *-down-> "1" MeetingsTab
MainWindow *-down-> "1" HelpTab

PersonListPanel -down-> "*" PersonCard

MainWindow -left-|> UiPart

UiManager -right-> Logic
MainWindow -left-> Logic

MainWindow -[hidden]-|> UiPart
@enduml
